using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MadplanVbkAsp.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Foods",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Aeblesyre = table.Column<string>(nullable: true),
                    Alanin = table.Column<string>(nullable: true),
                    AlfaTokoferol = table.Column<string>(nullable: true),
                    AlfaTokotrienol = table.Column<string>(nullable: true),
                    Alkohol = table.Column<string>(nullable: true),
                    AndreFedtsyrer = table.Column<string>(nullable: true),
                    AndreMaettedeFedtsyrer = table.Column<string>(nullable: true),
                    AndreMonoumaettedeFedtsyrer = table.Column<string>(nullable: true),
                    AndrePolymaettedeFedtsyrer = table.Column<string>(nullable: true),
                    AndreSukkerarter = table.Column<string>(nullable: true),
                    Arginin = table.Column<string>(nullable: true),
                    Arsen = table.Column<string>(nullable: true),
                    Aske = table.Column<string>(nullable: true),
                    Asparaginsyre = table.Column<string>(nullable: true),
                    Avitamin = table.Column<string>(nullable: true),
                    B12vitamin = table.Column<string>(nullable: true),
                    B1vitamin = table.Column<string>(nullable: true),
                    B2vitaminRiboflavin = table.Column<string>(nullable: true),
                    B6vitamin = table.Column<string>(nullable: true),
                    Bcaroten = table.Column<string>(nullable: true),
                    Benzoesyre = table.Column<string>(nullable: true),
                    Biotin = table.Column<string>(nullable: true),
                    Bly = table.Column<string>(nullable: true),
                    C100 = table.Column<string>(nullable: true),
                    C120 = table.Column<string>(nullable: true),
                    C140 = table.Column<string>(nullable: true),
                    C141n5 = table.Column<string>(nullable: true),
                    C150 = table.Column<string>(nullable: true),
                    C151 = table.Column<string>(nullable: true),
                    C160 = table.Column<string>(nullable: true),
                    C161n7 = table.Column<string>(nullable: true),
                    C161trans = table.Column<string>(nullable: true),
                    C170 = table.Column<string>(nullable: true),
                    C171n7 = table.Column<string>(nullable: true),
                    C180 = table.Column<string>(nullable: true),
                    C181n7 = table.Column<string>(nullable: true),
                    C181n9 = table.Column<string>(nullable: true),
                    C181trans = table.Column<string>(nullable: true),
                    C182conjA = table.Column<string>(nullable: true),
                    C182n6 = table.Column<string>(nullable: true),
                    C182trans = table.Column<string>(nullable: true),
                    C183n3 = table.Column<string>(nullable: true),
                    C183n6 = table.Column<string>(nullable: true),
                    C184n3 = table.Column<string>(nullable: true),
                    C200 = table.Column<string>(nullable: true),
                    C201n11 = table.Column<string>(nullable: true),
                    C201n9 = table.Column<string>(nullable: true),
                    C201trans = table.Column<string>(nullable: true),
                    C202n6 = table.Column<string>(nullable: true),
                    C203n3 = table.Column<string>(nullable: true),
                    C203n6 = table.Column<string>(nullable: true),
                    C204n3 = table.Column<string>(nullable: true),
                    C204n6 = table.Column<string>(nullable: true),
                    C205n3 = table.Column<string>(nullable: true),
                    C220 = table.Column<string>(nullable: true),
                    C221n11 = table.Column<string>(nullable: true),
                    C221n9 = table.Column<string>(nullable: true),
                    C221trans = table.Column<string>(nullable: true),
                    C225n3 = table.Column<string>(nullable: true),
                    C226n3 = table.Column<string>(nullable: true),
                    C240 = table.Column<string>(nullable: true),
                    C241n9 = table.Column<string>(nullable: true),
                    C40 = table.Column<string>(nullable: true),
                    C60 = table.Column<string>(nullable: true),
                    C80 = table.Column<string>(nullable: true),
                    Cadaverin = table.Column<string>(nullable: true),
                    Cadmium = table.Column<string>(nullable: true),
                    Calcium = table.Column<string>(nullable: true),
                    Cellulose = table.Column<string>(nullable: true),
                    Chlorid = table.Column<string>(nullable: true),
                    Cholesterol = table.Column<string>(nullable: true),
                    Chrom = table.Column<string>(nullable: true),
                    Citronsyre = table.Column<string>(nullable: true),
                    Cobolt = table.Column<string>(nullable: true),
                    CrudeFibre = table.Column<string>(nullable: true),
                    Cvitamin = table.Column<string>(nullable: true),
                    Cystin = table.Column<string>(nullable: true),
                    D3cholecalciferol = table.Column<string>(nullable: true),
                    DeltaTokoferol = table.Column<string>(nullable: true),
                    DisacchariderTotal = table.Column<string>(nullable: true),
                    Dmaelkesyre = table.Column<string>(nullable: true),
                    Dvitamin = table.Column<string>(nullable: true),
                    Eddikesyre = table.Column<string>(nullable: true),
                    EnergiKcal = table.Column<string>(nullable: true),
                    EnergiKj = table.Column<string>(nullable: true),
                    Evitamin = table.Column<string>(nullable: true),
                    FCF = table.Column<string>(nullable: true),
                    FedtTotal = table.Column<string>(nullable: true),
                    FedtsyrerTotal = table.Column<string>(nullable: true),
                    Folat = table.Column<string>(nullable: true),
                    FoodId = table.Column<int>(nullable: false),
                    FritFolat = table.Column<string>(nullable: true),
                    Fructose = table.Column<string>(nullable: true),
                    Galaktose = table.Column<string>(nullable: true),
                    GammaTokoferol = table.Column<string>(nullable: true),
                    Glutaminsyre = table.Column<string>(nullable: true),
                    Glycin = table.Column<string>(nullable: true),
                    Glycose = table.Column<string>(nullable: true),
                    HET = table.Column<string>(nullable: true),
                    Hexoses = table.Column<string>(nullable: true),
                    Histamin = table.Column<string>(nullable: true),
                    Histidin = table.Column<string>(nullable: true),
                    Hydroxycholecalciferol = table.Column<string>(nullable: true),
                    Inositol = table.Column<string>(nullable: true),
                    Isoleucin = table.Column<string>(nullable: true),
                    Jern = table.Column<string>(nullable: true),
                    Jod = table.Column<string>(nullable: true),
                    K1vitamin = table.Column<string>(nullable: true),
                    Kalium = table.Column<string>(nullable: true),
                    Kobber = table.Column<string>(nullable: true),
                    Kostfiber = table.Column<string>(nullable: true),
                    KulhydratDeklaration = table.Column<string>(nullable: true),
                    KulhydratDifferens = table.Column<string>(nullable: true),
                    KulhydratTilgaengelig = table.Column<string>(nullable: true),
                    Lactose = table.Column<string>(nullable: true),
                    Lascorbinsyre = table.Column<string>(nullable: true),
                    Ldehydroascorbinsyre = table.Column<string>(nullable: true),
                    Leucin = table.Column<string>(nullable: true),
                    Lignin = table.Column<string>(nullable: true),
                    Lmaelkesyre = table.Column<string>(nullable: true),
                    Lysin = table.Column<string>(nullable: true),
                    MaelkesyreTotal = table.Column<string>(nullable: true),
                    Magnesium = table.Column<string>(nullable: true),
                    Maltitol = table.Column<string>(nullable: true),
                    Maltose = table.Column<string>(nullable: true),
                    Mangan = table.Column<string>(nullable: true),
                    Mannitol = table.Column<string>(nullable: true),
                    Methionin = table.Column<string>(nullable: true),
                    Molybdbaen = table.Column<string>(nullable: true),
                    MonosacchariderTotal = table.Column<string>(nullable: true),
                    NDF = table.Column<string>(nullable: true),
                    Name = table.Column<string>(nullable: true),
                    Natrium = table.Column<string>(nullable: true),
                    Ncf = table.Column<string>(nullable: true),
                    Niacin = table.Column<string>(nullable: true),
                    Niacin2 = table.Column<string>(nullable: true),
                    Nikkel = table.Column<string>(nullable: true),
                    OrganiskeSyrerTotal = table.Column<string>(nullable: true),
                    Oxalsyre = table.Column<string>(nullable: true),
                    Pantothensyre = table.Column<string>(nullable: true),
                    Pentoses = table.Column<string>(nullable: true),
                    Phenylalanin = table.Column<string>(nullable: true),
                    Phenylethylamin = table.Column<string>(nullable: true),
                    Phosphor = table.Column<string>(nullable: true),
                    Prolin = table.Column<string>(nullable: true),
                    ProteinDeklaration = table.Column<string>(nullable: true),
                    ProteinTotal = table.Column<string>(nullable: true),
                    Putrescin = table.Column<string>(nullable: true),
                    QuantityConververId = table.Column<int>(nullable: false),
                    Raffinose = table.Column<string>(nullable: true),
                    Retinol = table.Column<string>(nullable: true),
                    Saccharose = table.Column<string>(nullable: true),
                    Selen = table.Column<string>(nullable: true),
                    Serin = table.Column<string>(nullable: true),
                    Serotonin = table.Column<string>(nullable: true),
                    Sorbitol = table.Column<string>(nullable: true),
                    Spermidin = table.Column<string>(nullable: true),
                    Spermin = table.Column<string>(nullable: true),
                    Stivelse = table.Column<string>(nullable: true),
                    SukkerAlkoholerTotal = table.Column<string>(nullable: true),
                    SukkerarterIalt = table.Column<string>(nullable: true),
                    SumMaettedeFedtsyrer = table.Column<string>(nullable: true),
                    SumMonoumaettedeFedtsyrer = table.Column<string>(nullable: true),
                    SumPolymaettedeFedtsyrer = table.Column<string>(nullable: true),
                    Sumn3Fedtsyrer = table.Column<string>(nullable: true),
                    Sumn6Fedtsyrer = table.Column<string>(nullable: true),
                    Svind = table.Column<string>(nullable: true),
                    Thiamin = table.Column<string>(nullable: true),
                    Threonin = table.Column<string>(nullable: true),
                    TilsatSukker = table.Column<string>(nullable: true),
                    Tin = table.Column<string>(nullable: true),
                    Torstof = table.Column<string>(nullable: true),
                    TotalN = table.Column<string>(nullable: true),
                    TransFedtsyrerTotal = table.Column<string>(nullable: true),
                    Tryptofan = table.Column<string>(nullable: true),
                    Tyramin = table.Column<string>(nullable: true),
                    Tyrosin = table.Column<string>(nullable: true),
                    UronicAcids = table.Column<string>(nullable: true),
                    Valin = table.Column<string>(nullable: true),
                    Vand = table.Column<string>(nullable: true),
                    Zink = table.Column<string>(nullable: true),
                    kviksolv = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Foods", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Foods");
        }
    }
}
